apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector: 
    matchLabels:
      run: frontend
  template:
    metadata: 
      labels:
        run: frontend
    spec:
      containers:
        - name: demoapp
          image: tanzuacrdemo.azurecr.io/utdtest:latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: acr-satya