apiVersion: apps/v1
kind: Deployment
metadata:
  lables:
    test-demo-app
  name: frontend
spec:
  replicas: 1
  selector: 
    matchLabels:
      test-demo-app
  template:
    metadata: 
      labels:
        test-demo-app
    spec:
      containers:
        - name: frontend
          image: tanzuacrdemo.azurecr.io/utdtest:latest
          ports:
          - containerPort: 8080
      imagePullSecrets:
        - name: acr-satya