apiVersion: v1
kind: Service
metadata:
    labels:
        app: frontend
        service: frontend-svc
    name: frontend-svc
spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: http-frontend
    selector:
        app: frontend
    type: ClusterIP
